# Generated by Django 5.2.1 on 2025-05-26 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencybalance',
            options={'verbose_name': 'Currency Balance', 'verbose_name_plural': 'Currency Balances'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operation', 'verbose_name_plural': 'Operations'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Watches'},
        ),
        migrations.AlterModelTableComment(
            name='rate',
            table_comment='Rates Of Currencies',
        ),
        migrations.AlterModelTableComment(
            name='watch',
            table_comment='Watches Of Currencies',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telegram',
        ),
        migrations.AddField(
            model_name='account',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TelegramVerificationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Verification Link',
                'verbose_name_plural': 'Telegram Verification Links',
                'db_table': 'telegram_verification_link',
                'db_table_comment': 'Telegram Verification Links',
            },
        ),
    ]
