# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.

services:
  server:
    build:
      context: .
    # deploy:
    #   replicas: 1
    ports:
      - target: 8000
        published: 8000
    env_file:
      - "config/.env"
    image: fiit:latest
    develop:
      watch:
        - path: backend/
          action: sync
          target: fiit/backend/
        - path: frontend/
          action: sync
          target: fiit/frontend/
        - path: config/
          action: sync+restart
          target: fiit/config/
    restart: always
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    networks:
      - network

  db:
    # TODO
    # Дирегктива `context: .` ломает сборку
    # Разобраться, почему, и где должен быть контекст у PostgreSQL
    # build:
    #   context: .
    # deploy:
    #   replicas: 1
    image: postgres:15
    ports:
      - target: 5432
        published: 5432
    env_file:
      - "config/.env"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # TODO
    # Не находятся переменные среды:
    # warning msg="The \"POSTGRES_PASSWORD\" variable is not set.
    # Научиться собирать переменные среды в compose
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U '${POSTGRES_USER}' -d '${POSTGRES_DB}'"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # environment:
    #   PGPASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
