# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.

services:
  server:
    build:
      context: .
    deploy:
      replicas: 1
    ports:
      - target: 8000
        published: 8000
    env_file:
      - "config/.env"
    image: fiit:latest
    develop:
      watch:
        - path: backend/
          action: sync
          target: fiit/backend/
        - path: frontend/
          action: sync
          target: fiit/frontend/
        - path: config/
          action: sync+restart
          target: fiit/config/
    restart: always
    depends_on:
      - db
    networks:
      - network

  db:
    build:
      context: .
    deploy:
      replicas: 1
    ports:
      - target: 5432
        published: 5432
    env_file:
      - "config/.env"
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
